-- Create "register_attempts" table
CREATE TABLE "public"."register_attempts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "mobile" character varying(20) NOT NULL, "one_time_code" integer NOT NULL DEFAULT (floor(((random() * (900000)::double precision) + (100000)::double precision)))::integer, "used_at" timestamp NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "public"."users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "bio" character varying(1000) NOT NULL, "birth_date" date NOT NULL, "last_location_long" numeric(9,6) NULL, "last_location_lat" numeric(9,6) NULL, "mobile" character varying(20) NOT NULL, "last_active" timestamp NULL, "email" character varying(100) NOT NULL, "sex" smallint NOT NULL, "interested_in" smallint NOT NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"));
-- Create "likes" table
CREATE TABLE "public"."likes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NULL, "target_id" uuid NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "likes_target_id_fkey" FOREIGN KEY ("target_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "likes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "matches" table
CREATE TABLE "public"."matches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_1_id" uuid NULL, "user_2_id" uuid NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "matches_user_1_id_fkey" FOREIGN KEY ("user_1_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "matches_user_2_id_fkey" FOREIGN KEY ("user_2_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "messages" table
CREATE TABLE "public"."messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NULL, "target_id" uuid NULL, "message" character varying(4000) NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "messages_target_id_fkey" FOREIGN KEY ("target_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "messages_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "user_photos" table
CREATE TABLE "public"."user_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NULL, "url" character varying(4000) NULL, "hash" character varying(64) NOT NULL, "created_at" timestamp NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY ("id"), CONSTRAINT "user_photos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
