// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register_attempt_create.sql

package db

import (
	"context"
)

const registerAttemptCreate = `-- name: RegisterAttemptCreate :one

INSERT INTO register_attempts (
  mobile
) VALUES (
  $1
)
RETURNING id, mobile, one_time_code, used_at, created_at
`

// CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
func (q *Queries) RegisterAttemptCreate(ctx context.Context, mobile string) (RegisterAttempt, error) {
	row := q.db.QueryRowContext(ctx, registerAttemptCreate, mobile)
	var i RegisterAttempt
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.OneTimeCode,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
