// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register_attempts.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const registerAttemptConfirm = `-- name: RegisterAttemptConfirm :one

UPDATE register_attempts
SET
    used_at = NOW()
WHERE id = $1
  AND one_time_code = $2
  AND used_at IS NULL
  AND created_at >= NOW() - INTERVAL '10 seconds'
RETURNING id
`

type RegisterAttemptConfirmParams struct {
	ID          uuid.UUID `json:"id"`
	OneTimeCode int32     `json:"one_time_code"`
}

// Note: you can use :exec if it doesnt return anything
func (q *Queries) RegisterAttemptConfirm(ctx context.Context, arg RegisterAttemptConfirmParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, registerAttemptConfirm, arg.ID, arg.OneTimeCode)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const registerAttemptCreate = `-- name: RegisterAttemptCreate :one

INSERT INTO register_attempts (
  mobile
) VALUES (
  $1
)
RETURNING id, mobile, one_time_code, used_at, created_at
`

func (q *Queries) RegisterAttemptCreate(ctx context.Context, mobile string) (RegisterAttempt, error) {
	row := q.db.QueryRowContext(ctx, registerAttemptCreate, mobile)
	var i RegisterAttempt
	err := row.Scan(
		&i.ID,
		&i.Mobile,
		&i.OneTimeCode,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}
