// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const userCreate = `-- name: UserCreate :one

INSERT INTO users (
  name, bio, birth_date, mobile, email, sex, interested_in
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, bio, birth_date, last_location_long, last_location_lat, mobile, last_active, email, sex, interested_in, created_at
`

type UserCreateParams struct {
	Name         string    `json:"name"`
	Bio          string    `json:"bio"`
	BirthDate    time.Time `json:"birth_date"`
	Mobile       string    `json:"mobile"`
	Email        string    `json:"email"`
	Sex          int16     `json:"sex"`
	InterestedIn int16     `json:"interested_in"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.Name,
		arg.Bio,
		arg.BirthDate,
		arg.Mobile,
		arg.Email,
		arg.Sex,
		arg.InterestedIn,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BirthDate,
		&i.LastLocationLong,
		&i.LastLocationLat,
		&i.Mobile,
		&i.LastActive,
		&i.Email,
		&i.Sex,
		&i.InterestedIn,
		&i.CreatedAt,
	)
	return i, err
}

const userDelete = `-- name: UserDelete :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) UserDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, userDelete, id)
	return err
}

const userGet = `-- name: UserGet :one
SELECT id, name, bio, birth_date, last_location_long, last_location_lat, mobile, last_active, email, sex, interested_in, created_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) UserGet(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, userGet, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BirthDate,
		&i.LastLocationLong,
		&i.LastLocationLat,
		&i.Mobile,
		&i.LastActive,
		&i.Email,
		&i.Sex,
		&i.InterestedIn,
		&i.CreatedAt,
	)
	return i, err
}

const userUpdate = `-- name: UserUpdate :one
UPDATE users
  set
  name = $8,
  bio = $7,
  birth_date = $6,
  mobile = $5,
  email = $4,
  sex = $3,
  interested_in = $2
WHERE id = $1
RETURNING id, name, bio, birth_date, last_location_long, last_location_lat, mobile, last_active, email, sex, interested_in, created_at
`

type UserUpdateParams struct {
	ID           uuid.UUID `json:"id"`
	InterestedIn int16     `json:"interested_in"`
	Sex          int16     `json:"sex"`
	Email        string    `json:"email"`
	Mobile       string    `json:"mobile"`
	BirthDate    time.Time `json:"birth_date"`
	Bio          string    `json:"bio"`
	Name         string    `json:"name"`
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userUpdate,
		arg.ID,
		arg.InterestedIn,
		arg.Sex,
		arg.Email,
		arg.Mobile,
		arg.BirthDate,
		arg.Bio,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BirthDate,
		&i.LastLocationLong,
		&i.LastLocationLat,
		&i.Mobile,
		&i.LastActive,
		&i.Email,
		&i.Sex,
		&i.InterestedIn,
		&i.CreatedAt,
	)
	return i, err
}
