services:
  goapp:
    profiles:
      - goapp
    env_file: .env
    build:
      context: .
      dockerfile: ./goapp/goapp.dockerfile
      args:
        GOAPP_BASE_IMAGE: golang:1.26
    image: click/goapp
    container_name: click-goapp
    environment:
      APP_NAME: goapp
      DB_ADDR: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOAPP_PORT: ${GOAPP_PORT}
    ports:
      - ${GOAPP_PORT}:${GOAPP_PORT}
    command: /usr/bin/goapp
    depends_on:
      db:
        condition: service_started
    networks:
      - local
  
  db:
    env_file: .env
    build:
      dockerfile: ./build/db.dockerfile
      args:
        DB_BASE_IMAGE: postgres:latest
    image: click/db
    container_name: click-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - local

  # pgadmin:
  #   env_file: .env
  #   build:
  #     dockerfile: ./build/pgadmin.dockerfile
  #     args:
  #       PGADMIN_SERVERS_FILENAME: pgadmin_servers.json
  #       PGADMIN_BASE_IMAGE: dpage/pgadmin4:latest
  #   image: click/pgadmin
  #   container_name: click-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
  #     PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
  #   ports:
  #     - ${PGADMIN_PORT}:${PGADMIN_PORT}
  #   depends_on:
  #     db:
  #       condition: service_started
  #   networks:
  #     - local

networks:
  local:
    name: click_network
