version: '3.7'

services:
  dbserver:
    build:
      dockerfile: ./build/dbserver.dockerfile
      args:
        DB_BASE_IMAGE: ${DB_BASE_IMAGE}
    image: ${DB_CUSTOM_IMAGE_NAME}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - local

  pgadmin:
    build:
      dockerfile: ./build/pgadmin.dockerfile
      args:
        PGADMIN_SERVERS_FILENAME: ${PGADMIN_SERVERS_FILENAME}
        PGADMIN_BASE_IMAGE: ${PGADMIN_BASE_IMAGE}
    image: ${PGADMIN_CUSTOM_IMAGE_NAME}
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_PORT}
    ports:
      - ${PGADMIN_PORT}:${PGADMIN_PORT}
    depends_on:
      dbserver:
        condition: service_started
    networks:
      - local

  goapp:
    build:
      context: .
      dockerfile: ./build/goapp.dockerfile
      args:
        GOAPP_BASE_IMAGE: ${GOAPP_BASE_IMAGE}
    image: ${GOAPP_IMAGE_NAME}
    container_name: ${GOAPP_CONTAINER_NAME}
    environment:
      APP_NAME: goapp
      DB_ADDR: ${DB_ADDR}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GOAPP_PORT: ${GOAPP_PORT}
    ports:
      - ${GOAPP_PORT}:${GOAPP_PORT}
    command: /usr/bin/goapp
    depends_on:
      dbserver:
        condition: service_started
    networks:
      - local
      
networks:
  local:
    name: ${NETWORK_NAME}