version: '3.7'

services:

  dbserver:
    image: postgres:15.1
    container_name: dbserver
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: default
    ports:
      - 5432:5432
    volumes:
      - $PWD/tmp/pgdata:/var/lib/postgresql/data
    networks:
      - local

  migration:
    image: dpage/pgadmin4:6.18
    container_name: migration
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psql.email
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      dbserver:
        condition: service_started
    volumes:
      - $PWD/pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - local

  pgadmin:
    image: dpage/pgadmin4:6.18
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@psql.email
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    depends_on:
      dbserver:
        condition: service_started
    volumes:
      - $PWD/pgadmin_servers.json:/pgadmin4/servers.json
    networks:
      - local

  goapp:
    image: click/goapp:current
    container_name: goapp
    environment:
      - APP_NAME=goapp
    ports:
      - 3030:3030
    command: /usr/bin/goapp
    depends_on:
      dbserver:
        condition: service_started
    networks:
      - local
      
networks:
  local:
    name: click_network