// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Like struct {
	ID        int64
	UserID    int64
	TargetID  int64
	CreatedAt time.Time
}

type Match struct {
	ID        int64
	User1ID   int64
	User2ID   int64
	CreatedAt time.Time
}

type Message struct {
	ID        int64
	UserID    int64
	TargetID  int64
	Message   sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID               int64
	Name             string
	Bio              sql.NullString
	BirthDate        time.Time
	LastLocationLong sql.NullString
	LastLocationLat  sql.NullString
	Mobile           sql.NullString
	LastActive       sql.NullTime
	Email            sql.NullString
	Sex              interface{}
	InterestedIn     int16
	CreatedAt        sql.NullTime
}

type UserPhoto struct {
	ID        int64
	UserID    int64
	Url       sql.NullString
	Hash      string
	CreatedAt time.Time
}
