// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Like struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.NullUUID `json:"user_id"`
	TargetID  uuid.NullUUID `json:"target_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Match struct {
	ID        uuid.UUID     `json:"id"`
	User1ID   uuid.NullUUID `json:"user_1_id"`
	User2ID   uuid.NullUUID `json:"user_2_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Message struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"user_id"`
	TargetID  uuid.NullUUID  `json:"target_id"`
	Message   sql.NullString `json:"message"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Bio              string         `json:"bio"`
	BirthDate        time.Time      `json:"birth_date"`
	LastLocationLong sql.NullString `json:"last_location_long"`
	LastLocationLat  sql.NullString `json:"last_location_lat"`
	Mobile           string         `json:"mobile"`
	LastActive       sql.NullTime   `json:"last_active"`
	Email            string         `json:"email"`
	Sex              int16          `json:"sex"`
	InterestedIn     int16          `json:"interested_in"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type UserPhoto struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.NullUUID  `json:"user_id"`
	Url       sql.NullString `json:"url"`
	Hash      string         `json:"hash"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
