// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: update_user.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :one
UPDATE users
  set
  name = $8,
  bio = $7,
  birth_date = $6,
  mobile = $5,
  email = $4,
  sex = $3,
  interested_in = $2
WHERE id = $1
RETURNING id, name, bio, birth_date, last_location_long, last_location_lat, mobile, last_active, email, sex, interested_in, created_at
`

type UpdateUserParams struct {
	ID           uuid.UUID   `json:"id"`
	InterestedIn int16       `json:"interested_in"`
	Sex          interface{} `json:"sex"`
	Email        string      `json:"email"`
	Mobile       string      `json:"mobile"`
	BirthDate    time.Time   `json:"birth_date"`
	Bio          string      `json:"bio"`
	Name         string      `json:"name"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.InterestedIn,
		arg.Sex,
		arg.Email,
		arg.Mobile,
		arg.BirthDate,
		arg.Bio,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BirthDate,
		&i.LastLocationLong,
		&i.LastLocationLat,
		&i.Mobile,
		&i.LastActive,
		&i.Email,
		&i.Sex,
		&i.InterestedIn,
		&i.CreatedAt,
	)
	return i, err
}
