// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const userDelete = `-- name: UserDelete :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) UserDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, userDelete, id)
	return err
}
