// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user_create.sql

package db

import (
	"context"
	"time"
)

const userCreate = `-- name: UserCreate :one

INSERT INTO users (
  name, bio, birth_date, mobile, email, sex, interested_in
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, bio, birth_date, last_location_long, last_location_lat, mobile, last_active, email, sex, interested_in, created_at
`

type UserCreateParams struct {
	Name         string    `json:"name"`
	Bio          string    `json:"bio"`
	BirthDate    time.Time `json:"birth_date"`
	Mobile       string    `json:"mobile"`
	Email        string    `json:"email"`
	Sex          int16     `json:"sex"`
	InterestedIn int16     `json:"interested_in"`
}

// CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.Name,
		arg.Bio,
		arg.BirthDate,
		arg.Mobile,
		arg.Email,
		arg.Sex,
		arg.InterestedIn,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.BirthDate,
		&i.LastLocationLong,
		&i.LastLocationLat,
		&i.Mobile,
		&i.LastActive,
		&i.Email,
		&i.Sex,
		&i.InterestedIn,
		&i.CreatedAt,
	)
	return i, err
}
